### PR TITLE
feat: Set E element as ElasticsearchQueryBuilder's attributes

### PR DESCRIPTION
**Pull request by qcoumes**
This allows to override elements such as EMust, EWord, ..., without
the need of overriding ElasticsearchQueryBuilder's methods.

- #73

### CODE REVIEW

**Review by alexgarel — APPROVED** [review]
Cool move @qcoumes !

Before merging, could you eventually add a line at the end of docs/source/quick_start.rst to tell it's possible (giving a sensible use case) ?

**Comment by alexgarel** [comment]
@qcoumes; I just merged PR #71 which adds a new operator, you might want to add it before merging.

**Comment by alexgarel** [comment]
BTW: please use "Squash and merge" :-)

**Comment by qcoumes** [comment]
I did not notice you merged the new operator directly onto this branch, so I rebased master and added it from there. Sorry for the force-push.

I added the new element and updated the documentation with a new sub-section `Modifying the generated queries` under the section `Transforming to elastic query`.

I don't usually write `.rst` and have nothing to test locally, I hope I did not make any syntax errors.

I can't select squash and merge ("Only those with write access to this repository can merge pull requests."), but there is only one commit after the force push anyway.

**Comment by alexgarel** [comment]
Really cool @qcoumes. Thank you.

No pb for rebasing and force pushing :-)

**Comment by alexgarel** [comment]
BTW a simple way to test documentation rendering was simply to visit the file on you branch : https://github.com/qcoumes/luqum/blob/feat/elasticsearch_visitor_element_override/docs/source/quick_start.rst :-)

**Pull request merged**
