### PR TITLE
Remove unused SEPARATOR token

### PR DESCRIPTION
**Pull request by Peter92**
Thought I may as well do the PR mentioned in #47 as it was quite simple :)

I removed it from `parsetab.py` too for the sake of keeping things clean, though I'm aware that the file is auto generated.

### CODE REVIEW

**Comment by alexgarel** [comment]
@Peter92 doctest are failing ! This is due to the `Illegal character ' '` error log.

**Comment by Peter92** [comment]
Ah my bad, it was working fine on my own project so I didn't run the tests after cleaning up the last few references. I'll take it as a learning experience to always run them if available haha.

**Comment by Peter92** [comment]
Appears to be fine now aside from a random error

**Comment by alexgarel** [comment]
Ok, thanks. For the failing test, we shall drop python3.4 support I guess.

**Pull request merged**
